### ISSUE TITLE
dev: implement new callbacks of `query.Trace` because of `ydb-go-sdk/v3.77.0`

### ISSUE THREAD

**Issue by pelageech** [ydb-platform/ydb-go-sdk-otel#24]
New callbacks are needed to be implemented: `OnExec`, `OnQuery` and so on.

_The issue exists just to see it to be done._

**Comment by asmyasnikov** [comment]
new callback allowed in https://github.com/ydb-platform/ydb-go-sdk-otel/releases/tag/v0.7.9
